eureka:
  client:
    #Eureka服务的地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #用于表示在猜测主机名时，服务器的IP地址应该与操作系统报告的主机名相对应。(注册服务和客户端如果在一台机器上则无需配置)
    prefer-ip-address: true
spring:
  cloud:
    config:
      #应用(application)的名字
      name: base
      #环境(profile)标识
      profile: dev
      #分支的名字
      label: master
      #配置中心的地址
#      uri: http://localhost:8888
      discovery:
        #开启Eureka的注册的服务的发现
        enabled: true
        #在Eureka中注册的配置中心服务端的名字
        service-id: HbaseService-config
    #MQ配置
    rabbitmq:
      host: 192.168.80.128
      port: 5672
      username: guest
      password: guest